language: go

go:
  - master

services:
  - mysql

before_install:
  - sudo mysql < script/schema.sql

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
