nginx:
  build: "nginx"
  ports:
    - "80:80"
  links:
    - goshare:goshare
  volumes:
    - ~/goshare-website/build:/usr/share/nginx/html
goshare:
  build: "../../"
  ports:
    - "8080"
  environment:
    DSN: "root:123@tcp(db)/goshare?charset=utf8&parseTime=true"
  links:
    - db:db
db:
  image: mysql
  ports:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123