swagger: "2.0"
info:
  description: GoShare项目后端接口文档
  version: "0.0.2"
  title: "Goshare"
  termsOfService: "https://www.bestlang.cn/"
  contact:
    email: "ligenhw@outlook.com"
  license:
    name: "MIT"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "www.bestlang.cn"
basePath: "/api"
tags:
- name: "article"
  description: "文章"
- name: "user"
  description: "用户"
- name: "comment"
  description: "评论"
schemes:
- "https"
paths:
  /article:
    get:
      tags:
      - "article"
      summary: 查询文章列表
      description: ""
      operationId: GetArticles
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ArticlesResp"
        405:
          description: "Invalid input"
  /comments:
    get:
      tags:
      - "comment"
      summary: 获取评论
      description: ""
      operationId: GetComment
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: blogId
        description: "评论博客id"
        required: true
        type: integer
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CommentsResp"
        405:
          description: "Invalid input"
    post:
      tags:
      - "comment"
      summary: 创建评论
      description: ""
      operationId: CreateComment
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "评论结构"
        required: true
        schema:
          $ref: "#/definitions/CreateCommentsReq"
      responses:
        200:
          description: "successful operation"

# model define
definitions:
  Article:
    type: object
    properties:
      id:
        type: integer
        format: int32
      user_id:
        type: integer
        format: int32
      title:
        type: integer
        format: int32
      content:
        type: string
      time:
        type: string
        format: date-time

  User:
    type: object
    properties:
      id:
        type: integer
        format: int32
      username:
        type: string
      password:
        type: string
      avatarurl:
        type: string
      time:
        type: string
        format: date-time

  Comment:
    type: object
    properties:
      parentId:
        type: integer
        format: int32
      parentUserId:
        type: integer
        format: int32
      parentContent:
        type: string
      parentTime:
        type: string
      subComments:
        type: array
        items:
          $ref: "#/definitions/SubComment"
  
  SubComment:
    type: object
    properties:
      id:
        type: integer
        format: int32
      blogId:
        type: integer
        format: int32
      userId:
        type: string
      parentId:
        type: string
      replyTo:
        type: string
      content:
        type: string
      time:
        type: string
        format: date-time
  
  CreateCommentsReq:
    type: object
    properties:
      blogId: 
        type: string
      parentCommentId:
        type: string
      replyTo:
        type: string
      content:
        type: string
  ArticlesResp:
    type: object
    properties:
      article:
        $ref: '#/definitions/Article'
      user:
        $ref: '#/definitions/User'
  CommentsResp:
    type: object
    properties:
      comments: 
        type: array
        items:
          $ref: "#/definitions/Comment"
      users:
        type: array
        items:
          $ref: "#/definitions/User"
  